### ISSUE TITLE
git-p4 failes with `NameError: name 'CalledProcessError' is not defined'` when P4 fails

### ISSUE THREAD

**Issue by cazador481** [gitgitgadget/git#1239]
Looks like the git-p4.py doesn't import CalledProcessError from subprocess.  Throughout the code the code tries to throw the CalledProcessError errors, and can't.
Example failure:
```python
Traceback (most recent call last):
  File "/home/utils/git-2.35.1/libexec/git-core/git-p4", line 4367, in <module>
    main()
  File "/home/utils/git-2.35.1/libexec/git-core/git-p4", line 4361, in main
    if not cmd.run(args):
  File "/home/utils/git-2.35.1/libexec/git-core/git-p4", line 4034, in run
    return self.rebase()
  File "/home/utils/git-2.35.1/libexec/git-core/git-p4", line 4051, in rebase
    system("git rebase %s" % upstream)
  File "/home/utils/git-2.35.1/libexec/git-core/git-p4", line 409, in system
    raise CalledProcessError(retcode, cmd)
NameError: name 'CalledProcessError' is not defined'
```

**Comment by dscho** [comment]
@cazador481 if you meant to report a bug, this is not the right venue. The resources at https://git-scm.com/community suggest the right venue: Take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

The issues in this repository are meant only to track project ideas for new contributors.
